version: "3.3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - MYSQL_HOST=mysql:3306
      - MYSQL_USERNAME=logging
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=logging
      - AUTH0_DOMAIN
      - AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET
    ports:
      - 8080:8080

  mysql:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=logging
      - MYSQL_PASSWORD=changeme
      - MySQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=logging
