
site_name: BFI IIIF Auditing
repo_url: https://github.com/bfidatadigipres/bfi-iiif-logging/

theme:
  name: mkdocs

nav:
  - Home: index.md
  - Architecture Decision Records:
      - 01. Choice of RDBMS: adr/0001-choice-of-rdbms.md
      - 02. Choice of Authentication provider: adr/0002-choice-of-auth-provider.md
      - 03. Choice of Technology and Framework: adr/0003-choice-of-technology-and-framework.md
      - 04. Universal Viewer customisations: adr/0004-universal-viewer-customisations.md

plugins:
  - techdocs-core
