
site_name: BFI IIIF Auditing
repo_url: https://github.com/bfidatadigipres/bfi-iiif-logging/

theme:
  name: mkdocs

nav:
  - Home: README.md
  - Architecture Decision Records:
      - 01. Choice of RDBMS: docs/adr/0001-choice-of-rdbms.md
      - 02. Choice of Authentication provider: docs/adr/0002-choice-of-auth-provider.md
      - 03. Choice of Technology and Framework: docs/adr/0003-choice-of-technology-and-framework.md
      - 04. Universal Viewer customisations: docs/adr/0004-universal-viewer-customisations.md
