name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
  build_and_push:
    runs-on: ubuntu-20.04
    steps:
      - name: Extract branch name
        run: echo "normalized_branch_name=$(stripped=${GITHUB_REF#refs/heads/} && echo ${stripped/\//-})" >> $GITHUB_ENV

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build and test application
        run: ./gradlew check
        env:
          AUTH0_DOMAIN: ${{ secrets.AUTH0_TEST_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_TEST_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_TEST_CLIENT_SECRET }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          registry: ghcr.io

      - name: Create Docker container
        run: ./gradlew bootBuildImage --imageName=ghcr.io/bfidatadigipres/bfi-iiif-load-balancer:${{ env.normalized_branch_name }}

      - name: Push Docker containers
        run: |
          docker tag ghcr.io/bfidatadigipres/bfi-iiif-load-balancer:${{ env.normalized_branch_name }} ghcr.io/bfidatadigipres/bfi-iiif-load-balancer:${{ github.sha }}
          docker push ghcr.io/bfidatadigipres/bfi-iiif-load-balancer:${{ env.normalized_branch_name }}
          docker push ghcr.io/bfidatadigipres/bfi-iiif-load-balancer:${{ github.sha }}
