name: cypress
on:
  workflow_dispatch:
jobs:
  run_cypress:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v1
      - name: NPM install
        run: npm install
      - name: Run NPM tests
        run: npm test
